version: '3.1'
services:
   redis-server:
      image: redis:5-alpine
      restart: always
      container_name: redis
      ports:
        - 6379:6379
      volumes:
        - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        - ./data:/data
      command: redis-server /usr/local/etc/redis/redis.conf