version: "3.1"
services:
   kibana:
    image: kibana:6.7.0
    container_name: sc-kibana
    volumes:
      - ./data/kibana/logs:/var/logs/kibana
      - ./devops/kibana.yml:/etc/kibana/kibana.yml
    ports:
      - 5601:5601
    networks:
      - es-net

networks:
  es-net:
    external: true