version: '3.1'
services:
   mysql-server:
      image: mysql:8
      restart: always
      container_name: mysql
      environment:
          MYSQL_ROOT_PASSWORD: "Admin123"
      command:
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=1
      volumes:
         - ./conf/my.cnf:/etc/mysql/my.cnf
         - ./data:/var/lib/mysql
           # - ./init:/docker-entrypoint-initdb.d/
      ports:
         - 3306:3306
   adminer:
      image: adminer
      restart: always
      ports:
         - 8090:8080