version: '3.1'
services:
   sentinel:
      image: sentinel
      restart: always
      container_name: sentinel
      volumes:
        - ./logs:/root/logs
        - ./config:/home/sentinel/config
      ports:
        - '8408:8080'